### ISSUE TITLE
fbx-conv fails to build with fbx-sdk 2014.2.1

### ISSUE THREAD

**Issue by aginiewicz** [libgdx/fbx-conv#42]
Everything worked nicely with fbx-sdk 2014.2, but after update to 2014.2.1 I get error:

```
../../src/readers/FbxConverter.h:596:27: error: ‘class fbxsdk_2014_2_1::FbxScene’ has no member named ‘GetEvaluator’
     animStack->GetScene()->GetEvaluator()->SetContext(animStack);
                            ^
```

Full build output: http://pastebin.com/m2HtV2Lc
